/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type MachineReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'machine'
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  label?: string
  name?: string
  slug?: Slug
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  machines?: Array<
    {
      _key: string
    } & MachineReference
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type IndustryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'industry'
}

export type SolutionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'solution'
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type Machine = {
  _id: string
  _type: 'machine'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  label?: string
  price?: number
  isHighlighted?: boolean
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  industries?: Array<
    {
      _key: string
    } & IndustryReference
  >
  solutions?: Array<
    {
      _key: string
    } & SolutionReference
  >
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  features?: Array<{
    key?: string
    value?: string
    _type: 'keyValuePair'
    _key: string
  }>
  specifications?: Array<{
    key?: string
    value?: string
    _type: 'keyValuePair'
    _key: string
  }>
}

export type Solution = {
  _id: string
  _type: 'solution'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  label?: string
  description?: string
  isHighlighted?: boolean
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  challenges?: Array<string>
  solution_text?: Array<string>
  machines?: Array<
    {
      _key: string
    } & MachineReference
  >
}

export type Industry = {
  _id: string
  _type: 'industry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  label?: string
  description?: string
  isHighlighted?: boolean
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  challenges?: Array<string>
  solution_text?: Array<string>
  machines?: Array<
    {
      _key: string
    } & MachineReference
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | MachineReference
  | Category
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | IndustryReference
  | SolutionReference
  | CategoryReference
  | Machine
  | Solution
  | Industry
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: app/data/getCategories.ts
// Variable: CATEGORY_QUERY
// Query: *[_type == "category"] | order(name asc) {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " packaging machinery category"),    description  }
export type CATEGORY_QUERY_RESULT = Array<{
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
}>

// Source: app/data/getCategoryBySlug.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " system setup"),    description,    "machines": coalesce(machines[]-> {      _id,      label,      "slug": slug.current,      name,      price,      description,      "imageUrl": image.asset->url,      "imageAlt": coalesce(image.alt, name + " variant overview"),      "features": coalesce(features[]{key, value}, []),      "specifications": coalesce(specifications[]{key, value}, [])    }, [])  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  machines:
    | Array<{
        _id: string
        label: string | null
        slug: string | null
        name: string | null
        price: number | null
        description: string | null
        imageUrl: string | null
        imageAlt: string | null
        features:
          | Array<{
              key: string | null
              value: string | null
            }>
          | Array<never>
        specifications:
          | Array<{
              key: string | null
              value: string | null
            }>
          | Array<never>
      }>
    | Array<never>
} | null

// Source: app/data/getHighlightedMachines.ts
// Variable: HIGHLIGHTED_MACHINES_QUERY
// Query: *[_type == "machine" && isHighlighted == true] | order(_updatedAt desc) {    _id,    "slug": slug.current,    name,    label,    price,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " primary packaging hardware feature"),    description,    "features": coalesce(features[]{key, value}, []),    "specifications": coalesce(specifications[]{key, value}, [])  }
export type HIGHLIGHTED_MACHINES_QUERY_RESULT = Array<{
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  price: number | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  features:
    | Array<{
        key: string | null
        value: string | null
      }>
    | Array<never>
  specifications:
    | Array<{
        key: string | null
        value: string | null
      }>
    | Array<never>
}>

// Source: app/data/getHighlightedSolutions.ts
// Variable: HIGHLIGHTED_SOLUTIONS_QUERY
// Query: *[_type == "solution" && isHighlighted == true] | order(_updatedAt desc) {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " custom automation package summary"),    description,    "challenges": coalesce(challenges, []),    "solution_text": coalesce(solution_text, [])  }
export type HIGHLIGHTED_SOLUTIONS_QUERY_RESULT = Array<{
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  challenges: Array<string> | Array<never>
  solution_text: Array<string> | Array<never>
}>

// Source: app/data/getIndustries.ts
// Variable: INDUSTRIES_QUERY
// Query: *[_type == "industry"] | order(name asc) {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " manufacturing workflow"),    description,    "challenges": coalesce(challenges, []),    "solution_text": coalesce(solution_text, [])  }
export type INDUSTRIES_QUERY_RESULT = Array<{
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  challenges: Array<string> | Array<never>
  solution_text: Array<string> | Array<never>
}>

// Source: app/data/getIndustryBySlug.ts
// Variable: INDUSTRY_BY_SLUG_QUERY
// Query: *[_type == "industry" && slug.current == $slug][0] {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " enterprise facility"),    description,    "challenges": coalesce(challenges, []),    "solution_text": coalesce(solution_text, []),    "machines": coalesce(machines[]-> {      _id,      label,      "slug": slug.current,      name,      description,      price,      "imageUrl": image.asset->url,      "imageAlt": coalesce(image.alt, name + " production line machine"),      "features": coalesce(features[]{key, value}, []),      "specifications": coalesce(specifications[]{key, value}, [])    }, [])  }
export type INDUSTRY_BY_SLUG_QUERY_RESULT = {
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  challenges: Array<string> | Array<never>
  solution_text: Array<string> | Array<never>
  machines:
    | Array<{
        _id: string
        label: string | null
        slug: string | null
        name: string | null
        description: string | null
        price: number | null
        imageUrl: string | null
        imageAlt: string | null
        features:
          | Array<{
              key: string | null
              value: string | null
            }>
          | Array<never>
        specifications:
          | Array<{
              key: string | null
              value: string | null
            }>
          | Array<never>
      }>
    | Array<never>
} | null

// Source: app/data/getMachineBySlug.ts
// Variable: MACHINE_BY_SLUG_QUERY
// Query: *[_type == "machine" && slug.current == $slug][0] {    _id,    "slug": slug.current,    name,    label,    price,    description,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " packaging machinery system close up spec"),    "features": coalesce(features[]{key, value}, []),    "specifications": coalesce(specifications[]{key, value}, []),        "categories": coalesce(category[]-> {      _id,      "slug": slug.current,      name,      label,      "imageUrl": image.asset->url,      "imageAlt": coalesce(image.alt, name + " configuration category")    }, []),        "industries": coalesce(industries[]-> {      _id,      label,      name,      "slug": slug.current,      description,      "imageUrl": image.asset->url,      "imageAlt": coalesce(image.alt, name + " sector match")    }, []),        "solutions": coalesce(solutions[]-> {      _id,      label,      name,      description,      "slug": slug.current,      "imageUrl": image.asset->url,      "imageAlt": coalesce(image.alt, name + " engineering application configuration")    }, [])  }
export type MACHINE_BY_SLUG_QUERY_RESULT = {
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  price: number | null
  description: string | null
  imageUrl: string | null
  imageAlt: string | null
  features:
    | Array<{
        key: string | null
        value: string | null
      }>
    | Array<never>
  specifications:
    | Array<{
        key: string | null
        value: string | null
      }>
    | Array<never>
  categories: Array<never>
  industries:
    | Array<{
        _id: string
        label: string | null
        name: string | null
        slug: string | null
        description: string | null
        imageUrl: string | null
        imageAlt: string | null
      }>
    | Array<never>
  solutions:
    | Array<{
        _id: string
        label: string | null
        name: string | null
        description: string | null
        slug: string | null
        imageUrl: string | null
        imageAlt: string | null
      }>
    | Array<never>
} | null

// Source: app/data/getMachines.ts
// Variable: MACHINES_QUERY
// Query: *[_type == "machine"] | order(_createdAt desc) {    _id,    "slug": slug.current,    name,    label,    price,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " industrial packaging equipment"),    description,    "features": coalesce(features[]{key, value}, []),    "specifications": coalesce(specifications[]{key, value}, [])  }
export type MACHINES_QUERY_RESULT = Array<{
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  price: number | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  features:
    | Array<{
        key: string | null
        value: string | null
      }>
    | Array<never>
  specifications:
    | Array<{
        key: string | null
        value: string | null
      }>
    | Array<never>
}>

// Source: app/data/getSolutionBySlug.ts
// Variable: SOLUTION_BY_SLUG_QUERY
// Query: *[_type == "solution" && slug.current == $slug][0] {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " processing line"),    description,    "challenges": coalesce(challenges, []),    "solution_text": coalesce(solution_text, []),    "machines": coalesce(machines[]-> {      _id,      label,      "slug": slug.current,      name,      price,      description,      "imageUrl": image.asset->url,      "imageAlt": coalesce(image.alt, name + " variant layout"),      "features": coalesce(features[]{key, value}, []),      "specifications": coalesce(specifications[]{key, value}, [])    }, [])  }
export type SOLUTION_BY_SLUG_QUERY_RESULT = {
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  challenges: Array<string> | Array<never>
  solution_text: Array<string> | Array<never>
  machines:
    | Array<{
        _id: string
        label: string | null
        slug: string | null
        name: string | null
        price: number | null
        description: string | null
        imageUrl: string | null
        imageAlt: string | null
        features:
          | Array<{
              key: string | null
              value: string | null
            }>
          | Array<never>
        specifications:
          | Array<{
              key: string | null
              value: string | null
            }>
          | Array<never>
      }>
    | Array<never>
} | null

// Source: app/data/getSolutions.ts
// Variable: SOLUTIONS_QUERY
// Query: *[_type == "solution"] | order(name asc) {    _id,    "slug": slug.current,    name,    label,    "imageUrl": image.asset->url,    "imageAlt": coalesce(image.alt, name + " material handling solution"),    description,    "challenges": coalesce(challenges, []),    "solution_text": coalesce(solution_text, [])  }
export type SOLUTIONS_QUERY_RESULT = Array<{
  _id: string
  slug: string | null
  name: string | null
  label: string | null
  imageUrl: string | null
  imageAlt: string | null
  description: string | null
  challenges: Array<string> | Array<never>
  solution_text: Array<string> | Array<never>
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "category"] | order(name asc) {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " packaging machinery category"),\n    description\n  }\n': CATEGORY_QUERY_RESULT
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " system setup"),\n    description,\n    "machines": coalesce(machines[]-> {\n      _id,\n      label,\n      "slug": slug.current,\n      name,\n      price,\n      description,\n      "imageUrl": image.asset->url,\n      "imageAlt": coalesce(image.alt, name + " variant overview"),\n      "features": coalesce(features[]{key, value}, []),\n      "specifications": coalesce(specifications[]{key, value}, [])\n    }, [])\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "machine" && isHighlighted == true] | order(_updatedAt desc) {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    price,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " primary packaging hardware feature"),\n    description,\n    "features": coalesce(features[]{key, value}, []),\n    "specifications": coalesce(specifications[]{key, value}, [])\n  }\n': HIGHLIGHTED_MACHINES_QUERY_RESULT
    '\n  *[_type == "solution" && isHighlighted == true] | order(_updatedAt desc) {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " custom automation package summary"),\n    description,\n    "challenges": coalesce(challenges, []),\n    "solution_text": coalesce(solution_text, [])\n  }\n': HIGHLIGHTED_SOLUTIONS_QUERY_RESULT
    '\n  *[_type == "industry"] | order(name asc) {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " manufacturing workflow"),\n    description,\n    "challenges": coalesce(challenges, []),\n    "solution_text": coalesce(solution_text, [])\n  }\n': INDUSTRIES_QUERY_RESULT
    '\n  *[_type == "industry" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " enterprise facility"),\n    description,\n    "challenges": coalesce(challenges, []),\n    "solution_text": coalesce(solution_text, []),\n    "machines": coalesce(machines[]-> {\n      _id,\n      label,\n      "slug": slug.current,\n      name,\n      description,\n      price,\n      "imageUrl": image.asset->url,\n      "imageAlt": coalesce(image.alt, name + " production line machine"),\n      "features": coalesce(features[]{key, value}, []),\n      "specifications": coalesce(specifications[]{key, value}, [])\n    }, [])\n  }\n': INDUSTRY_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "machine" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    price,\n    description,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " packaging machinery system close up spec"),\n    "features": coalesce(features[]{key, value}, []),\n    "specifications": coalesce(specifications[]{key, value}, []),\n    \n    "categories": coalesce(category[]-> {\n      _id,\n      "slug": slug.current,\n      name,\n      label,\n      "imageUrl": image.asset->url,\n      "imageAlt": coalesce(image.alt, name + " configuration category")\n    }, []),\n    \n    "industries": coalesce(industries[]-> {\n      _id,\n      label,\n      name,\n      "slug": slug.current,\n      description,\n      "imageUrl": image.asset->url,\n      "imageAlt": coalesce(image.alt, name + " sector match")\n    }, []),\n    \n    "solutions": coalesce(solutions[]-> {\n      _id,\n      label,\n      name,\n      description,\n      "slug": slug.current,\n      "imageUrl": image.asset->url,\n      "imageAlt": coalesce(image.alt, name + " engineering application configuration")\n    }, [])\n  }\n': MACHINE_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "machine"] | order(_createdAt desc) {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    price,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " industrial packaging equipment"),\n    description,\n    "features": coalesce(features[]{key, value}, []),\n    "specifications": coalesce(specifications[]{key, value}, [])\n  }\n': MACHINES_QUERY_RESULT
    '\n  *[_type == "solution" && slug.current == $slug][0] {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " processing line"),\n    description,\n    "challenges": coalesce(challenges, []),\n    "solution_text": coalesce(solution_text, []),\n    "machines": coalesce(machines[]-> {\n      _id,\n      label,\n      "slug": slug.current,\n      name,\n      price,\n      description,\n      "imageUrl": image.asset->url,\n      "imageAlt": coalesce(image.alt, name + " variant layout"),\n      "features": coalesce(features[]{key, value}, []),\n      "specifications": coalesce(specifications[]{key, value}, [])\n    }, [])\n  }\n': SOLUTION_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "solution"] | order(name asc) {\n    _id,\n    "slug": slug.current,\n    name,\n    label,\n    "imageUrl": image.asset->url,\n    "imageAlt": coalesce(image.alt, name + " material handling solution"),\n    description,\n    "challenges": coalesce(challenges, []),\n    "solution_text": coalesce(solution_text, [])\n  }\n': SOLUTIONS_QUERY_RESULT
  }
}
